### ISSUE TITLE
Error: Unable to resolve module `./divider/divider-short` 

### ISSUE THREAD

**Issue by hanayashiki** [florianstahr/react-native-settings-components#10]
Hi, I am eager to try your impressive work, but I got the following error when I was trying to install.
```
error: Error: Unable to resolve module `./divider/divider-short` from `node_modules/react-native-settings-components/src/index.js`: 
```

I am using a ejected expo project and here is my `babel.config.js`:

```
module.exports = function (api) {
    api.cache(true);
    return {
        presets: ['babel-preset-expo'],
        plugins: [
            [
                'module-resolver',
                {
                    alias: {
                        app: ".",
                    },
                },
            ],
        ],
    };
};
```

I checked `node_modules` and can assure that the file is there:

![image](https://user-images.githubusercontent.com/26056783/84215567-8490c180-aa7b-11ea-8d79-bfbb65eb50dd.png)

What might be the problem? Thanks in advance..

**Comment by hanayashiki** [comment]
Found a solution by myself:
```
module.exports = {
    // ...
    resolver: {
        //...
        sourceExts: ['jsx', 'js', 'tsx', 'ts']
        //..
    },
};
```

Add this line to `metro.config.js`

**Comment by peterdluong** [comment]
I'm using a standard react native project so would that affect the issue? I tried inserting what you said in the `metro.config.js` file and it did not resolve the error. Do you know if there are any other ways to fix it?
